esphome:
  name: m5poe
  friendly_name: m5poe

packages:
  base: !include m5poe.yaml

daikin_x10a:
  uart_id: daikin_uart
  mode: 1
  registers:
    - { mode: 0, registryID: 0x00, offset: 0, convid: 802, dataSize: 0, dataType: -1, label: "*Refrigerant type" }
    - { mode: 0, registryID: 0x00, offset: 0, convid: 152, dataSize: 1, dataType: -1, label: "Sensor Data Qty" }
    - { mode: 0, registryID: 0x00, offset: 1, convid: 152, dataSize: 1, dataType: -1, label: "INV compressor Qty" }
    - { mode: 0, registryID: 0x00, offset: 2, convid: 152, dataSize: 1, dataType: -1, label: "STD compressor Qty" }
    - { mode: 0, registryID: 0x00, offset: 3, convid: 152, dataSize: 1, dataType: -1, label: "Fan Data Qty" }
    - { mode: 0, registryID: 0x00, offset: 4, convid: 152, dataSize: 1, dataType: -1, label: "Expansion Valve Data Qty" }
    - { mode: 0, registryID: 0x00, offset: 5, convid: 152, dataSize: 1, dataType: -1, label: "4 Way Valve Data Qty" }
    - { mode: 0, registryID: 0x00, offset: 6, convid: 152, dataSize: 1, dataType: -1, label: "Crank Case Heater Qty" }
    - { mode: 0, registryID: 0x00, offset: 7, convid: 152, dataSize: 1, dataType: -1, label: "Solenoid valve Qty" }
    - { mode: 0, registryID: 0x00, offset: 8, convid: 152, dataSize: 1, dataType: -1, label: "Max. connectable indoor units" }
    - { mode: 0, registryID: 0x00, offset: 9, convid: 152, dataSize: 1, dataType: -1, label: "Connected Indoor Unit Qty" }
    - { mode: 0, registryID: 0x00, offset: 10, convid: 152, dataSize: 1, dataType: -1, label: "O/U MPU ID (xx)" }
    - { mode: 0, registryID: 0x00, offset: 11, convid: 152, dataSize: 1, dataType: -1, label: "O/U MPU ID (yy)" }
    - { mode: 0, registryID: 0x00, offset: 12, convid: 105, dataSize: 1, dataType: -1, label: "O/U capacity (kW)" }
    - { mode: 1, registryID: 0x10, offset: 0, convid: 217, dataSize: 1, dataType: -1, label: "Operation Mode" }
    - { mode: 1, registryID: 0x10, offset: 1, convid: 307, dataSize: 1, dataType: -1, label: "Thermostat ON/OFF" }
    - { mode: 0, registryID: 0x10, offset: 1, convid: 306, dataSize: 1, dataType: -1, label: "Restart standby" }
    - { mode: 0, registryID: 0x10, offset: 1, convid: 305, dataSize: 1, dataType: -1, label: "Startup Control" }
    - { mode: 0, registryID: 0x10, offset: 1, convid: 304, dataSize: 1, dataType: -1, label: "Defrost Operation" }
    - { mode: 0, registryID: 0x10, offset: 4, convid: 203, dataSize: 1, dataType: -1, label: "Error type (O/U)" }
    - { mode: 0, registryID: 0x10, offset: 5, convid: 204, dataSize: 1, dataType: -1, label: "Error Code (O/U)" }
    - { mode: 0, registryID: 0x20, offset: 0, convid: 105, dataSize: 2, dataType: 1, label: "R1T-Outdoor air temp." }
    - { mode: 0, registryID: 0x60, offset: 2, convid: 315, dataSize: 1, dataType: -1, label: "I/U operation mode" }
    - { mode: 0, registryID: 0x60, offset: 3, convid: 204, dataSize: 1, dataType: -1, label: "Error Code (I/U)" }
    - { mode: 0, registryID: 0x60, offset: 5, convid: 203, dataSize: 1, dataType: -1, label: "Error type (I/U)" }
    - { mode: 0, registryID: 0x60, offset: 7, convid: 105, dataSize: 2, dataType: 1, label: "DHW setpoint" }
    - { mode: 0, registryID: 0x60, offset: 9, convid: 105, dataSize: 2, dataType: 1, label: "LW setpoint (main)" }
    - { mode: 0, registryID: 0x61, offset: 2, convid: 105, dataSize: 2, dataType: 1, label: "Leaving water temp. before BUH (R1T)" }
    - { mode: 0, registryID: 0x61, offset: 4, convid: 105, dataSize: 2, dataType: 1, label: "Leaving water temp. after BUH (R2T)" }
    - { mode: 0, registryID: 0x61, offset: 6, convid: 105, dataSize: 2, dataType: 1, label: "Refrig. Temp. liquid side (R3T)" }
    - { mode: 0, registryID: 0x61, offset: 8, convid: 105, dataSize: 2, dataType: 1, label: "Inlet water temp.(R4T)" }
    - { mode: 0, registryID: 0x61, offset: 10, convid: 105, dataSize: 2, dataType: 1, label: "DHW tank temp. (R5T)" }
    - { mode: 0, registryID: 0x61, offset: 12, convid: 105, dataSize: 2, dataType: 1, label: "Indoor ambient temp. (R1T)" }
    - { mode: 0, registryID: 0x61, offset: 14, convid: 105, dataSize: 2, dataType: 1, label: "Ext. indoor ambient sensor (R6T)" }
    - { mode: 0, registryID: 0x62, offset: 9, convid: 105, dataSize: 2, dataType: -1, label: "Flow sensor (l/min)" }
    - { mode: 0, registryID: 0x63, offset: 14, convid: 161, dataSize: 1, dataType: -1, label: "Current measured by CT sensor of L1" }
    - { mode: 0, registryID: 0x63, offset: 15, convid: 161, dataSize: 1, dataType: -1, label: "Current measured by CT sensor of L2" }
    - { mode: 0, registryID: 0x63, offset: 16, convid: 161, dataSize: 1, dataType: -1, label: "Current measured by CT sensor of L3" }
